version: 1.0.0
name: YourDurabilitY
main: reieno.ydurability.Main
api-version: 1.16
author: PapaReiena2k3
description: Use a line of lore in items for custom durability.
commands:
  ydy:
    description: main and admin plugin command.
    permission: ydy.admin
  repairitems:
    description: shows the repair items of the item in main hand.
    aliases: [ri]
    permission: ydy.user
permissions:
  ydy.admin:
    description: acces to /ydy command
    default: op
  ydy.user:
    description: acces to /repairitems command
    default: op